classget/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectMultipleField, widgets, StringField, SubmitField


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class SearchClassForm(FlaskForm):
    syozoku_choices = [('全学共通教育科目', '全学共通教育科目'), ('商学部', '商学部'), ('経済学部', '経済学部'),
                       ('法学部', '法学部'), ('社会学部', '社会学部'), ('国際交流科目', '国際交流科目'), ('教職科目', '教職科目')]
    term_choices = [('春夏学期', '春夏学期'), ('春学期', '春学期'), ('夏学期', '夏学期'), ('秋冬学期', '秋冬学期'),
                    ('秋学期', '秋学期'), ('冬学期', '冬学期'), ('通年', '通年')]
    day_choices = [('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('他', '他')]
    time_choices = [('1', '１限'), ('2', '２限'), ('3', '３限'), ('4', '４限'), ('5', '５限'), ('他', '他')]
    draw_choices = [('抽選科目', '抽選科目'), ('抽選なし', '抽選なし')]
    keyword_choices = [('期末試験', '期末試験'), ('期末レポート', '期末レポート'), ('中間試験', '中間試験'),
                       ('中間レポート', '中間レポート'), ('出席', '出席'), ('課題(毎回)', '課題(毎回)'), ('課題(たまに)', '課題(たまに)'),
                       ('ライブ', 'ライブ'), ('オンデマンド', 'オンデマンド'), ('ライブ・オンデマ併用', 'ライブ・オンデマ併用'), ('対面', '対面'),
                       ('顔出しアリ', '顔出しアリ'), ('顔出しナシ', '顔出しナシ'),('今年度非開講','今年度非開講')]
    sort = MultiCheckboxField('時間割所属', choices=syozoku_choices)
    term = MultiCheckboxField('開講区分', choices=term_choices)
    day = MultiCheckboxField('曜日', choices=day_choices)
    time = MultiCheckboxField('時限', choices=time_choices)
    draw = MultiCheckboxField('抽選', choices=draw_choices)
    title = StringField('授業名')
    teacher = StringField('教授名')
    keyword = MultiCheckboxField('(避けたい)キーワード', choices=keyword_choices)
    submit = SubmitField('この条件で検索')

classget/admin/routes.py
from flask import Blueprint, url_for, request, render_template
from flask_login import current_user
from werkzeug.utils import redirect

from classget import db
from classget.admin.forms import UpdateClassForm
from classget.models import Subject

admin = Blueprint('admin', __name__)


@admin.route("/updateclass/<int:subject_id>", methods=["GET", "POST"])
def updateclass(subject_id):
    # UserIDが「admin」の場合だけ
    if current_user.is_authenticated and current_user.iduser == 'admin':
        subject = Subject.query.get_or_404(subject_id)
        form = UpdateClassForm()
        # 修正フォームが提出されたら、DBに適用する
        if form.validate_on_submit():
            subject.sort = form.sort.data
            subject.term = form.term.data
            subject.time = form.time.data
            subject.name = form.name.data
            subject.teacher = form.teacher.data
            subject.language = form.language.data
            subject.draw = form.draw.data
            subject.keyword = form.keyword.data
            db.session.commit()
            return redirect(url_for('reviews.classinfo', subject_id=subject_id))
        # ページを開いたら既存の情報がすでに入っている
        elif request.method == 'GET':
            form.sort.data = subject.sort
            form.term.data = subject.term
            form.time.data = subject.time
            form.name.data = subject.name
            form.teacher.data = subject.teacher
            form.language.data = subject.language
            form.draw.data = subject.draw
            form.keyword.data = subject.keyword
            return render_template('admin/update_class.html', subject=subject, form=form)
    else:
        return 'access denied'


@admin.route("/createclass", methods=["GET", "POST"])
def createclass():
    form = UpdateClassForm()
    if current_user.is_authenticated and current_user.iduser == 'admin':
        if form.validate_on_submit():
            new_subject = Subject(sort=form.sort.data, term=form.term.data, time=form.time.data, name=form.name.data,
                                  teacher=form.teacher.data, language=form.language.data, draw=form.draw.data,
                                  keyword=form.keyword.data)
            db.session.add(new_subject)
            db.session.commit()
            return redirect(url_for('reviews.classinfo', subject_id=new_subject.id))
    else:
        return 'access denied'

    return render_template('admin/createclass.html', form=form)

@admin.route("/report.html")
def report_html():
    return render_template('report.html')

classget/main/routes.py
import os

from flask import Blueprint, render_template, session, request, send_from_directory, current_app
from flask_login import current_user
from sqlalchemy import or_

from classget.main.forms import SearchClassForm
from classget.models import Subject, get_count, Review

main = Blueprint('main', __name__)


@main.route("/", methods=["GET", "POST"])
def mainpage():
    form = SearchClassForm()
    return render_template('main/mainpage.html', form=form)


@main.route("/searchresult", methods=['GET', 'POST'])
def searchresult():
    form = SearchClassForm()
    result = Subject.query
    if form.validate_on_submit():
        session['form.sort.data'] = form.sort.data
        session['form.term.data'] = form.term.data
        session['form.day.data'] = form.day.data
        session['form.time.data'] = form.time.data
        session['form.draw.data'] = form.draw.data
        session['form.title.data'] = form.title.data
        session['form.teacher.data'] = form.teacher.data
        session['form.keyword.data'] = form.keyword.data
    # 所属
    if session['form.sort.data']:
        result = result.filter(Subject.sort.in_(session['form.sort.data']))
    # 開講区分
    if session['form.term.data']:
        result = result.filter(Subject.term.in_(session['form.term.data']))
    # 曜日
    if session['form.day.data']:
        day = [0, 0, 0, 0, 0, 0]
        for i in range(len(session['form.day.data'])):
            day[i] = session['form.day.data'][i]
        result = result.filter(or_(Subject.time.like(f'%{day[0]}%'), Subject.time.like(f'%{day[1]}%'),
                                   Subject.time.like(f'%{day[2]}%'), Subject.time.like(f'%{day[3]}%'),
                                   Subject.time.like(f'%{day[4]}%'), Subject.time.like(f'%{day[5]}%')))
    # 時限
    if session['form.time.data']:
        time = [0, 0, 0, 0, 0, 0]
        for i in range(len(session['form.time.data'])):
            time[i] = session['form.time.data'][i]
        result = result.filter(or_(Subject.time.like(f'%{time[0]}%'), Subject.time.like(f'%{time[1]}%'),
                                   Subject.time.like(f'%{time[2]}%'), Subject.time.like(f'%{time[3]}%'),
                                   Subject.time.like(f'%{time[4]}%'), Subject.time.like(f'%{time[5]}%')))
    # 抽選
    if session['form.draw.data']:
        result = result.filter(Subject.draw.in_(session['form.draw.data']))
    # 授業名
    if session['form.title.data']:
        result = result.filter(Subject.name.like(f"%{session['form.title.data']}%"))
    # 教授名
    if session['form.teacher.data']:
        result = result.filter(Subject.teacher.like(f"%{session['form.teacher.data']}%"))
    # キーワード
    if session['form.keyword.data']:
        for keyword in session['form.keyword.data']:
            result = result.filter(Subject.keyword.notlike(f'%{keyword}%'))
    # 検索結果を１０個ずつ分けてページを作る
    page = request.args.get('page', 1, type=int)
    result_num = get_count(result)
    result = result.paginate(page=page, per_page=10)
    if not result:
        result = "検索結果がありません。"
    return render_template('main/searchresult.html', title='検索結果', result=result, get_count=get_count, form=form,
                           Review=Review, result_num=result_num)


@main.route('/about_us')
def aboutus():
    return render_template('main/aboutus.html', title='About Us')


@main.route('/ham_menu', methods=['POST'])
def ham_menu():
    action = request.form['action']
    if action == 'show_menu':
        if current_user.is_authenticated:
            return render_template('main/show_ham_menu.html')
        else:
            return render_template('main/nouser_show_ham_menu.html')
    elif action == 'close_menu':
        return render_template('main/close_ham_menu.html')
    else:
        pass


@main.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static/img/icon'), 'favicon.ico',
                               mimetype='image/vnd.microsoft.icon')


@main.route('/sw.js')
def sw_js():
    return send_from_directory(os.path.join(current_app.root_path, 'static/js'), 'sw.js')


@main.route('/mobile_install')
def mobile_install():
    return render_template('main/mobile_install.html')

classget/users/routes.py
import random

from flask import Blueprint, url_for, render_template, request
from flask_login import current_user, login_user, login_required, logout_user
from sqlalchemy import or_
from werkzeug.utils import redirect

from classget import bcrypt, db
from classget.models import User, Like, get_count, Subject, Review
from classget.users.forms import RegistrationForm, LoginForm, UpdateAccountForm

users = Blueprint('users', __name__)


@users.route("/createaccount", methods=['GET', 'POST'])
def createaccount():
    if current_user.is_authenticated:
        return redirect(url_for('main.mainpage'))
    form = RegistrationForm()
    # アカウント作成フォームを提出したら
    if form.validate_on_submit():
        # パスワードの暗号化
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # ユーザー情報をデータベースに入れる
        user = User(username=form.username.data, iduser=form.iduser.data, password=hashed_pw,
                    faculty=form.faculty.data, year=form.year.data)
        db.session.add(user)
        db.session.commit()
        # さっき作られたアカウントでログインさせる
        user = User.query.filter_by(iduser=form.iduser.data).first()
        login_user(user)
        # キャラ診断ページに送る
        return redirect(url_for('users.typetest'))
    return render_template('users/createaccount.html', title='アカウント作成', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.mainpage'))
    form = LoginForm()
    login_error = 0
    # ログインフォームを提出したら
    if form.validate_on_submit():
        # 入力したIDでユーザー情報を持ってくる
        user = User.query.filter_by(iduser=form.iduser.data).first()
        # そのユーザー情報のPWとログインフォームで入力したPWが一致する場合
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # ログインさせる
            login_user(user, remember=form.remember.data)
            # 行こうとしたページがあったらそのページに送る
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.mainpage'))
        # パスワードが一致しない場合：パスワードエラー
        else:
            login_error = 1
    return render_template('users/login.html', title='ログイン', form=form, login_error=login_error)


@users.route("/updateaccount", methods=['GET', 'POST'])
@login_required
def updateaccount():
    form = UpdateAccountForm()
    password_error = 0
    # アカウント修正フォームを提出した場合
    if form.validate_on_submit():
        # 入力したPWが現在のPWと一致したら
        if bcrypt.check_password_hash(current_user.password, form.current_password.data):
            # 修正情報をデータベースに入れる
            current_user.username = form.username.data
            current_user.faculty = form.faculty.data
            current_user.year = form.year.data
            db.session.commit()
            # パスワードを変更（新しいパスワードを入力した場合）
            if form.new_password.data:
                current_user.password = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
                db.session.commit()
            # 修正が終わったらマイページに戻る
            return redirect(url_for('users.mypage', my_term='春'))
        # 入力したPWが現在PWと一致しない場合：パスワードエラー
        else:
            password_error = 1
    # ページを読み取った場合に書いてあるデフォルトユーザー情報
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.faculty.data = current_user.faculty
        form.year.data = current_user.year

    return render_template('users/updateaccount.html', title='アカウント情報修正', form=form, password_error=password_error)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.mainpage'))


@users.route("/mypage/<my_term>")
@login_required
def mypage(my_term):
    image_file = url_for('static', filename='img/profile_pics/' + current_user.type + '.png')
    liked_subject = Like.query.filter_by(user_id=current_user.id)\
        .filter(or_(Like.subject_term.like('%{}%'.format(my_term)), Like.subject_term.like('%通年%'))).all()

    def timetable(i):
        result = []
        for l in liked_subject:
            for t in l.subject.time.split(','):
                if t == i:
                    result.append([l.subject.id, l.subject.name])
        return result
    return render_template('users/mypage.html', title='マイページ', image_file=image_file, liked=liked_subject,
                           timetable=timetable, my_term=my_term, User=User, Review=Review, get_count=get_count)


@users.route("/typetest", methods=['GET', 'POST'])
@login_required
def typetest():
    question = ['初対面の人と友達になることができる。', '人助けをすることが多い。', '課題の期限は絶対守るし、遅刻も絶対しない。',
                '普段ストレスや不安をあまり感じない性格を持っている。', '芸術や美術は結構好きだ。',
                'しばしば新しい冒険についてのアイデアが思い浮かぶ。', '他の人にどう思われるかはあまり気にしない。',
                '人との約束のためなら無理もする。', 'みんなで何かを成し遂げることが好きだ。', '面白い話で場を盛り上げることができる。']
    # すでにキャラ診断した人は結果ページに送る
    if current_user.type != 'none':
        return redirect(url_for('users.typeresult'))
    if request.method == 'POST':
        # formのdataから属性ごとにスコアを集計
        kaisou_score = int(request.form['Q1']) + int(request.form['Q10'])
        penguin_score = int(request.form['Q2']) + int(request.form['Q9'])
        iruka_score = int(request.form['Q3']) + int(request.form['Q8'])
        kame_score = int(request.form['Q4']) + int(request.form['Q7'])
        taco_score = int(request.form['Q5']) + int(request.form['Q6'])
        scores = {'海藻': kaisou_score, 'ペンギン': penguin_score, 'イルカ': iruka_score,
                  'カメ': kame_score, 'タコ': taco_score}
        # 一番高いスコアのキャラを入れる（複数の場合は共同１位のうちランダムで）
        max_score = max(scores.items(), key=lambda x: x[1])
        list_max = []
        for key, value in scores.items():
            if value == max_score[1]:
                list_max.append(key)
        current_user.type = random.choice(list_max)
        db.session.commit()
        return redirect(url_for('users.typeresult'))
    return render_template('users/typetest.html', question=question, title='キャラ診断')


@users.route("/typeresult", methods=['GET'])
@login_required
def typeresult():
    recommended_subjects = current_user.recommend_by_likes()
    catchphrase = {'海藻': '楽しいこと大好き！いつもノリノリな陽キャ',
                   'ペンギン': '冷たい氷も溶けちゃう優しさ！協力的なサポーター',
                   'イルカ': '頼まれたら裏切らない！信頼のメガバンク',
                   'カメ': '100人乗っても大丈夫！屋久杉のような安定感',
                   'タコ': '好奇心が止まらない！圧倒的な柔軟性'}
    description = {'海藻': ['おしゃべりで周りを楽しませることができる', '誰かと一緒にいることが好き', '自己主張がしっかりできる', '行動的なみんなのリーダータイプ'],
                   'ペンギン': ['やさしく、思いやりがある', '面倒見がいい', '共感力が高く、人の痛みが良く分かる', '人を疑わない'],
                   'イルカ': ['計画的に集中して物事に取り組むことができる', '責任感が強い', '誠実で頼られやすい', '時間や期限をきちんと守る'],
                   'カメ': ['大勢の人の前でもあまり緊張せずにいられる', '環境が変わってもなじみやすい', 'ものごとを根に持たない', 'あまり激しい感情にならない'],
                   'タコ': ['クリエイティブだとよく言われる', '原宿が好きだったりする', '人とかぶらないものが好き', '異なる解釈が可能な映画や本などに興味がある']}
    type_number = get_count(User.query.filter_by(type=current_user.type))
    user_number = get_count(User.query)
    type_com = get_count(User.query.filter_by(type=current_user.type, faculty='商学部'))
    type_eco = get_count(User.query.filter_by(type=current_user.type, faculty='経済学部'))
    type_law = get_count(User.query.filter_by(type=current_user.type, faculty='法学部'))
    type_soc = get_count(User.query.filter_by(type=current_user.type, faculty='社会学部'))
    type_proportion = "{:.1f}".format((type_number/user_number)*100)
    com_proportion = "{:.1f}".format((type_com/type_number)*100)
    eco_proportion = "{:.1f}".format((type_eco / type_number) * 100)
    law_proportion = "{:.1f}".format((type_law / type_number) * 100)
    soc_proportion = "{:.1f}".format((type_soc / type_number) * 100)
    return render_template('users/typeresult.html', recommended_subjects=recommended_subjects, type_pp=type_proportion,
                           com_pp=com_proportion, eco_pp=eco_proportion, law_pp=law_proportion, soc_pp=soc_proportion,
                           catchphrase=catchphrase, get_count=get_count, description=description, title='診断結果')


@users.route('/like', methods=['POST'])
@login_required
def like():
    subject_id = request.form['subject_id']
    action = request.form['action']
    subject = Subject.query.filter_by(id=subject_id).first_or_404()
    if action == 'like':
        current_user.like_subject(subject)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_subject(subject)
        db.session.commit()

    return render_template('users/like_button.html', subject=subject)

classget/templates/main/layout.html
<!DOCTYPE html>
<!---Ver 1.00--->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta name="description" content="一橋生のための楽しいクラス・ゲット・メディア！">
    <meta name="thumbnail" content="{{ url_for('static', filename='img/layout/main_logo.png') }}">

    <!--  PWA(iOS Safari)  -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="クラゲ百科事典">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='/img/icon/icon_152x152.png') }}">

    <!--  PWA(Android, PC)  -->
    <link rel="manifest" href="{{ url_for('static', filename='img/icon/manifest.json') }}">
    <script>
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('sw.js')
        .then((reg) => {
          console.log('sw_registered.', reg);
        });
      }
    </script>

    <title>
      {% if title %}
        クラゲ百科事典 - {{ title }}
      {% else %}
        クラゲ百科事典
      {% endif %}
    </title>
    <!--    font    -->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}" type="text/css">
    {% block stylesheet %}
    {% endblock %}
  </head>

  <body>
    <div class="layout">
      <div class="header"><!--ここからヘッダー-->
        <a>一橋生のための授業情報サイト</a>
        <div class="logo_div">
          <a href="{{ url_for('main.mainpage') }}">
            <img src="{{ url_for('static', filename='img/layout/main_logo.png') }}" class="mainlogo">
          </a>
        </div>
        <div class="presented">
          <p>presented by <img src="{{ url_for('static', filename='img/layout/hasclogo.png') }}"></p>
        </div>
      </div><!--ここまでヘッダー-->

      <div class="menu"><!--ここから緑のメニュー-->　　
        <div class="home">
          <a href="{{ url_for('main.mainpage') }}">ホーム</a>
          <!-- about usのページは未作成のためリンクなし-->
          <a href="{{ url_for('main.aboutus') }}">About Us</a>
        </div>
        <div class="login">
          {% if current_user.is_authenticated and current_user.iduser == 'admin' %}
            <a href="{{ url_for('admin.createclass') }}">授業追加</a>
          {% endif %}
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('users.typetest') }}">キャラ診断</a>
            <a href="{{ url_for('users.mypage', my_term='秋') }}">マイページ</a>
            <a href="{{ url_for('users.logout') }}">ログアウト</a>
          {% else %}
            <a href="{{ url_for('users.login') }}">ログイン</a>
            <a href="{{ url_for('users.createaccount') }}">アカウント作成</a>
          {% endif %}
        </div>

        <div class="ham-menu">
          <div class="hamburger-menu" id="show_menu">
            <a class="ham-letter" href="">menu</a>
            <a href=""><img class="menu_img" src="{{ url_for('static', filename='img/layout/hamburger_menu.png') }}"></a>
          </div>
        </div>
      </div><!--ここまで緑のメニュー -->
    </div>

  {% block contents %}
  {% endblock contents %}

  <footer class="footer">
      <div class="footer01">
        <a href="https://forms.gle/2RCNiDJHBTcjHWaa9" target="_blank" rel="noopener noreferrer" class="footer-btn">バグ報告・授業追加依頼はコチラ</a>
      </div>
      <div class="copyright">
        Copyright © 2021 HASC All rights reserved.
      </div>
      <div class="footer02">
        <ul class="footer-banner" style="list-style: none; padding-left: 0;">
          <li class="footer-banner1"><a href="https://twitter.com/hit_risyu2021?s=20" target="_blank" rel="noopener noreferrer"><img src="{{ url_for('static', filename='img/layout/footer-banner1.png') }}" alt="履修法入門（一橋大学非公式）"></a></li>
          <li class="footer-banner2"><a href="https://twitter.com/info_hit_u?s=20" target="_blank" rel="noopener noreferrer"><img src="{{ url_for('static', filename='img/layout/footer-banner2.png') }}" alt="一橋大学情報まとめ"></a></li>
        </ul>
      </div>
  </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/hamburger_menu.js') }}"></script>
  </body>
</html>

classget/templates/main/nouser_show_ham_menu.html
<div class="hamburger-menu" id="close_menu">
  <a class="ham-letter" href="">close</a>
  <a href=""><img id="close-img" class="menu_img" src="{{ url_for('static', filename='img/layout/close_menu.png') }}"></a>
</div>
<table class="ham">
    <tbody>
        <tr>
            <td><a href="{{ url_for('main.mainpage') }}">ホーム</a></td>
            <td><a href="{{ url_for('main.aboutus') }}">About Us</a></td>
        </tr>
        <tr>
            <td><a href="{{ url_for('users.login') }}">ログイン</a></td>
            <td><a href="{{ url_for('users.createaccount') }}">アカウント作成</a></td>
        </tr>
        <tr>
            <td><a href="{{ url_for('main.mobile_install') }}">スマホにインストール</a></td>
            <td></td>
        </tr>
    </tbody>
</table>

classget/templates/main/searchresult.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
    <!-- ここにCSSファイルをリンクする -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/searchresult.css') }}" type="text/css">
{% endblock %}


{% block contents %}
    <div class="whole_searchresult">
        <h3>　検索結果：　{{ result_num }}件</h3>
        <p class="warning">
            *授業情報は最新のシラバスや皆さんから集めた情報で更新していますが、
            情報の漏れがある可能性があります。
        </p>
        <div class="searchresult">
            {% for subject in result.items %}
                <a href="{{ url_for('reviews.classinfo', subject_id=subject.id) }}">
                    <div class="class">
                        <div class="result_header">
                            <div class="container">
                                <div class="class_name">{{ subject.name }}</div>
                                <div class="class_time">{{ subject.term }} {{ subject.time }}</div>
                            </div>
                            <div class="like_buttons{{ subject.id }}">
                                {% if current_user.is_authenticated and current_user.has_liked_subject(subject) %}
                                    <a href="" class="user_like_button" id="unlike_{{ subject.id }}">
                                        <img src="{{ url_for('static', filename='img/system/liked.png') }}">
                                    </a>
                                {% elif current_user.is_authenticated %}
                                    <a href="" class="user_like_button" id="like_{{ subject.id }}">
                                        <img src="{{ url_for('static', filename='img/system/unliked.png') }}">
                                    </a>
                                {% else %}
                                    <a href="{{ url_for('users.login') }}" class="like_button">
                                        <img src="{{ url_for('static', filename='img/system/unliked.png') }}">
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="class_sort">・{{ subject.sort }}　・{{ subject.draw }}</div>
                        <div class="class_sort">・教授：{{ subject.teacher }}　・言語：{{ subject.language }}</div>
                        <div class="rating">
                            <img src="{{ url_for('static', filename='img/system/rating_0.png') }}" width="32.5px">{{ subject.rating_count(0) }}
                            <img src="{{ url_for('static', filename='img/system/rating_1.png') }}" width="32.5px">{{ subject.rating_count(1) }}
                            <img src="{{ url_for('static', filename='img/system/rating_2.png') }}" width="32.5px">{{ subject.rating_count(2) }}
                            <div class="liked-number">(お気に入り{{ get_count(subject.likes) }}件)</div>
                        </div>
                        <div class="class_keyword">
                            {% for keyword in subject.keyword.split("　") %}
                                <span class="keyword">{{ keyword }}</span>
                            {% endfor %}
                        </div>
                        {% if current_user.is_authenticated and current_user.iduser == 'admin' %}
                            <a href="{{ url_for('admin.updateclass', subject_id=subject.id) }}"><button class="update_class_button">授業情報修正</button></a>
                        {% endif %}
                        <a class="see-detail" href="{{ url_for('reviews.classinfo', subject_id=subject.id) }}">授業の詳細を見る></a>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="page_number">
            {% for page_num in result.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if result.page == page_num %}
                        <a class="current_page_num" href="{{ url_for('main.searchresult', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="page_num" href="{{ url_for('main.searchresult', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/like_button.js') }}"></script>
{% endblock contents %}

classget/templates/main/show_ham_menu.html
<div class="hamburger-menu" id="close_menu">
  <a class="ham-letter" href="">close</a>
  <a href=""><img id="close-img" class="menu_img" src="{{ url_for('static', filename='img/layout/close_menu.png') }}"></a>
</div>
<table class="ham">
    <tbody>
        <tr>
            <td><a href="{{ url_for('main.mainpage') }}">ホーム</a></td>
            <td><a href="{{ url_for('main.aboutus') }}">About Us</a></td>
        </tr>
        <tr>
            <td><a href="{{ url_for('users.typetest') }}">キャラ診断</a></td>
            <td><a href="{{ url_for('users.mypage', my_term='秋') }}">マイページ</a></td>
        </tr>
        <tr>
            <td><a href="{{ url_for('main.mobile_install') }}">スマホにインストール</a></td>
            <td><a href="{{ url_for('users.logout') }}">ログアウト</a></td>
        </tr>
    </tbody>
</table>