classget/users/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError

from classget.models import User


class RegistrationForm(FlaskForm):
    faculty_choices = [('商学部', '商学部'), ('経済学部', '経済学部'), ('法学部', '法学部'), ('社会学部', '社会学部')]
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=1, max=16)])
    iduser = StringField('UserID',
                         validators=[DataRequired(), Length(min=2, max=45)])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    faculty = SelectField('Faculty', choices=faculty_choices)
    year = SelectField('Year', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    submit = SubmitField('アカウント作成')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('既に誰かが使用中のユーザー名です')

    def validate_iduser(self, iduser):
        user = User.query.filter_by(iduser=iduser.data).first()
        if user:
            raise ValidationError('既に誰かが使用中のIDです')


class LoginForm(FlaskForm):
    iduser = StringField('UserID',
                         validators=[DataRequired(), Length(min=2, max=50)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('ログイン')


class UpdateAccountForm(FlaskForm):
    faculty_choices = [('商学部', '商学部'), ('経済学部', '経済学部'), ('法学部', '法学部'), ('社会学部', '社会学部')]
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=10)])
    current_password = PasswordField('Current Password', validators=[DataRequired()])
    new_password = PasswordField('New Password(optional)')
    confirm_password = PasswordField('Confirm New Password(optional)',
                                     validators=[EqualTo('new_password')])
    faculty = SelectField('Faculty', choices=faculty_choices)
    year = SelectField('Year', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    submit = SubmitField('アカウント情報修正')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('既に誰かが使用中のユーザー名です')

classget/users/routes.py
import random

from flask import Blueprint, url_for, render_template, request
from flask_login import current_user, login_user, login_required, logout_user
from sqlalchemy import or_
from werkzeug.utils import redirect

from classget import bcrypt, db
from classget.models import User, Like, get_count, Subject, Review
from classget.users.forms import RegistrationForm, LoginForm, UpdateAccountForm

users = Blueprint('users', __name__)


@users.route("/createaccount", methods=['GET', 'POST'])
def createaccount():
    if current_user.is_authenticated:
        return redirect(url_for('main.mainpage'))
    form = RegistrationForm()
    # アカウント作成フォームを提出したら
    if form.validate_on_submit():
        # パスワードの暗号化
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # ユーザー情報をデータベースに入れる
        user = User(username=form.username.data, iduser=form.iduser.data, password=hashed_pw,
                    faculty=form.faculty.data, year=form.year.data)
        db.session.add(user)
        db.session.commit()
        # さっき作られたアカウントでログインさせる
        user = User.query.filter_by(iduser=form.iduser.data).first()
        login_user(user)
        # キャラ診断ページに送る
        return redirect(url_for('users.typetest'))
    return render_template('users/createaccount.html', title='アカウント作成', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.mainpage'))
    form = LoginForm()
    login_error = 0
    # ログインフォームを提出したら
    if form.validate_on_submit():
        # 入力したIDでユーザー情報を持ってくる
        user = User.query.filter_by(iduser=form.iduser.data).first()
        # そのユーザー情報のPWとログインフォームで入力したPWが一致する場合
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # ログインさせる
            login_user(user, remember=form.remember.data)
            # 行こうとしたページがあったらそのページに送る
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.mainpage'))
        # パスワードが一致しない場合：パスワードエラー
        else:
            login_error = 1
    return render_template('users/login.html', title='ログイン', form=form, login_error=login_error)


@users.route("/updateaccount", methods=['GET', 'POST'])
@login_required
def updateaccount():
    form = UpdateAccountForm()
    password_error = 0
    # アカウント修正フォームを提出した場合
    if form.validate_on_submit():
        # 入力したPWが現在のPWと一致したら
        if bcrypt.check_password_hash(current_user.password, form.current_password.data):
            # 修正情報をデータベースに入れる
            current_user.username = form.username.data
            current_user.faculty = form.faculty.data
            current_user.year = form.year.data
            db.session.commit()
            # パスワードを変更（新しいパスワードを入力した場合）
            if form.new_password.data:
                current_user.password = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
                db.session.commit()
            # 修正が終わったらマイページに戻る
            return redirect(url_for('users.mypage', my_term='春'))
        # 入力したPWが現在PWと一致しない場合：パスワードエラー
        else:
            password_error = 1
    # ページを読み取った場合に書いてあるデフォルトユーザー情報
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.faculty.data = current_user.faculty
        form.year.data = current_user.year

    return render_template('users/updateaccount.html', title='アカウント情報修正', form=form, password_error=password_error)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.mainpage'))


@users.route("/mypage/<my_term>")
@login_required
def mypage(my_term):
    image_file = url_for('static', filename='img/profile_pics/' + current_user.type + '.png')
    liked_subject = Like.query.filter_by(user_id=current_user.id)\
        .filter(or_(Like.subject_term.like('%{}%'.format(my_term)), Like.subject_term.like('%通年%'))).all()

    def timetable(i):
        result = []
        for l in liked_subject:
            for t in l.subject.time.split(','):
                if t == i:
                    result.append([l.subject.id, l.subject.name])
        return result
    return render_template('users/mypage.html', title='マイページ', image_file=image_file, liked=liked_subject,
                           timetable=timetable, my_term=my_term, User=User, Review=Review, get_count=get_count)


@users.route("/typetest", methods=['GET', 'POST'])
@login_required
def typetest():
    question = ['初対面の人と友達になることができる。', '人助けをすることが多い。', '課題の期限は絶対守るし、遅刻も絶対しない。',
                '普段ストレスや不安をあまり感じない性格を持っている。', '芸術や美術は結構好きだ。',
                'しばしば新しい冒険についてのアイデアが思い浮かぶ。', '他の人にどう思われるかはあまり気にしない。',
                '人との約束のためなら無理もする。', 'みんなで何かを成し遂げることが好きだ。', '面白い話で場を盛り上げることができる。']
    # すでにキャラ診断した人は結果ページに送る
    if current_user.type != 'none':
        return redirect(url_for('users.typeresult'))
    if request.method == 'POST':
        # formのdataから属性ごとにスコアを集計
        kaisou_score = int(request.form['Q1']) + int(request.form['Q10'])
        penguin_score = int(request.form['Q2']) + int(request.form['Q9'])
        iruka_score = int(request.form['Q3']) + int(request.form['Q8'])
        kame_score = int(request.form['Q4']) + int(request.form['Q7'])
        taco_score = int(request.form['Q5']) + int(request.form['Q6'])
        scores = {'海藻': kaisou_score, 'ペンギン': penguin_score, 'イルカ': iruka_score,
                  'カメ': kame_score, 'タコ': taco_score}
        # 一番高いスコアのキャラを入れる（複数の場合は共同１位のうちランダムで）
        max_score = max(scores.items(), key=lambda x: x[1])
        list_max = []
        for key, value in scores.items():
            if value == max_score[1]:
                list_max.append(key)
        current_user.type = random.choice(list_max)
        db.session.commit()
        return redirect(url_for('users.typeresult'))
    return render_template('users/typetest.html', question=question, title='キャラ診断')


@users.route("/typeresult", methods=['GET'])
@login_required
def typeresult():
    recommended_subjects = current_user.recommend_by_likes()
    catchphrase = {'海藻': '楽しいこと大好き！いつもノリノリな陽キャ',
                   'ペンギン': '冷たい氷も溶けちゃう優しさ！協力的なサポーター',
                   'イルカ': '頼まれたら裏切らない！信頼のメガバンク',
                   'カメ': '100人乗っても大丈夫！屋久杉のような安定感',
                   'タコ': '好奇心が止まらない！圧倒的な柔軟性'}
    description = {'海藻': ['おしゃべりで周りを楽しませることができる', '誰かと一緒にいることが好き', '自己主張がしっかりできる', '行動的なみんなのリーダータイプ'],
                   'ペンギン': ['やさしく、思いやりがある', '面倒見がいい', '共感力が高く、人の痛みが良く分かる', '人を疑わない'],
                   'イルカ': ['計画的に集中して物事に取り組むことができる', '責任感が強い', '誠実で頼られやすい', '時間や期限をきちんと守る'],
                   'カメ': ['大勢の人の前でもあまり緊張せずにいられる', '環境が変わってもなじみやすい', 'ものごとを根に持たない', 'あまり激しい感情にならない'],
                   'タコ': ['クリエイティブだとよく言われる', '原宿が好きだったりする', '人とかぶらないものが好き', '異なる解釈が可能な映画や本などに興味がある']}
    type_number = get_count(User.query.filter_by(type=current_user.type))
    user_number = get_count(User.query)
    type_com = get_count(User.query.filter_by(type=current_user.type, faculty='商学部'))
    type_eco = get_count(User.query.filter_by(type=current_user.type, faculty='経済学部'))
    type_law = get_count(User.query.filter_by(type=current_user.type, faculty='法学部'))
    type_soc = get_count(User.query.filter_by(type=current_user.type, faculty='社会学部'))
    type_proportion = "{:.1f}".format((type_number/user_number)*100)
    com_proportion = "{:.1f}".format((type_com/type_number)*100)
    eco_proportion = "{:.1f}".format((type_eco / type_number) * 100)
    law_proportion = "{:.1f}".format((type_law / type_number) * 100)
    soc_proportion = "{:.1f}".format((type_soc / type_number) * 100)
    return render_template('users/typeresult.html', recommended_subjects=recommended_subjects, type_pp=type_proportion,
                           com_pp=com_proportion, eco_pp=eco_proportion, law_pp=law_proportion, soc_pp=soc_proportion,
                           catchphrase=catchphrase, get_count=get_count, description=description, title='診断結果')


@users.route('/like', methods=['POST'])
@login_required
def like():
    subject_id = request.form['subject_id']
    action = request.form['action']
    subject = Subject.query.filter_by(id=subject_id).first_or_404()
    if action == 'like':
        current_user.like_subject(subject)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_subject(subject)
        db.session.commit()

    return render_template('users/like_button.html', subject=subject)

classget/templates/users/createaccount.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/createaccount.css') }}" type="text/css">
{% endblock %}

{% block contents %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <!--      アカウント作成タイトル      -->
            <legend>アカウント作成</legend>
            <!--     ID入力欄       -->
            <div class="userid">
                {% if form.iduser.errors %}
                    <div class="error">
                        {{ form.iduser(class="form_blank") }}
                        <!--       エラーメッセージ（IDは10文字以内にしてくださいとか）      -->
                        <div class="error_message">
                            {% for error in form.iduser.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.iduser(class="form_blank", placeholder="ユーザーID") }}
                {% endif %}
            </div>
            <!--      パスワード入力欄      -->
            <div class="password">
                {% if form.password.errors %}
                    <div class="error">
                        {{ form.password(class="form_blank", placeholder="パスワード") }}
                        <!--        エラーメッセージ（IDは10文字以内にしてくださいとか）        -->
                        <div class="error_message">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.password(class="form_blank", placeholder="パスワード") }}
                {% endif %}
            </div>
            <!--      パスワード確認入力欄      -->
            <div class="confirm_password">
                {% if form.confirm_password.errors %}
                    <div class="error">
                        {{ form.confirm_password(class="form_blank", placeholder="パスワード確認") }}
                        <div class="error_message">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form_blank", placeholder="パスワード確認") }}
                {% endif %}
            </div>
            <!--      ユーザー名入力欄      -->
            <div class="username">
                {% if form.username.errors %}
                    <div class="error">
                        {{ form.username(class="form_blank", placeholder="ユーザー名") }}
                        <div class="error_message">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.username(class="form_blank", placeholder="ユーザー名") }}
                {% endif %}
            </div>
            <!--     学部と学年のラベル／入力欄       -->
            <div class="syozoku">
                {{ form.faculty(class="form_blank", placeholder="学部") }}
                {{ form.year(class="form_blank", placeholder="学年") }}
            </div>
        </fieldset>
            <div>
            {{ form.submit(class="submit_button") }}
            </div>
    </form>
    <div class="already">
        <small>
            既にアカウント持ってますか？ <a href="{{ url_for('users.login') }}" class="have_account">ログイン</a>
        </small>
    </div>
{% endblock %}

classget/templates/users/like_button.html
{% if current_user.is_authenticated and current_user.has_liked_subject(subject) %}
    <a href="" class="user_like_button" id="unlike_{{ subject.id }}">
        <img class="like-button-img" src="{{ url_for('static', filename='img/system/liked.png') }}">
    </a>
{% elif current_user.is_authenticated %}
    <a href="" class="user_like_button" id="like_{{ subject.id }}">
        <img class="like-button-img" src="{{ url_for('static', filename='img/system/unliked.png') }}">
    </a>
{% else %}
    <a href="{{ url_for('users.login') }}" class="like_button">
        <img class="like-button-img" src="{{ url_for('static', filename='img/system/unliked.png') }}">
    </a>
{% endif %}

classget/templates/users/login.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}" type="text/css">
{% endblock %}

{% block contents %}

    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <!--      Loginタイトル         -->
            <legend>Login</legend>
            <!--       ID入力欄         -->
            <div class="userid">
                {% if form.iduser.errors %}
                    <div class="error">
                        {{ form.iduser(class="form_blank", placeholder="ユーザーID") }}
                        <div class="error_message">
                            {% for error in form.iduser.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.iduser(class="form_blank", placeholder="ユーザーID") }}
                {% endif %}
            </div>

            <!--     　　　パスワード入力欄           -->
            <div class="password">
                {% if form.password.errors %}
                    <div class="error">
                        {{ form.password(class="form_blank", placeholder="パスワード") }}
                        <div class="error_message">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {{ form.password(class="form_blank", placeholder="パスワード") }}
                {% endif %}
            </div>

            {% if login_error == 1 %}
                <!--      ログインに失敗した時にエラーメッセージ          -->
                <div class="error_message">
                    IDとPWをもう一度ご確認ください。
                </div>
            {% endif %}

            <!--      Remember　Me　チェックボックス          -->
            <div class="remember_me">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>

        <!--     Loginボタン       -->
        <div class="login_button">
            {{ form.submit(class="login_button") }}
        </div>
    </form>

    <!--　　アカウント作成に　　-->
    <div class="need-account-block">
        <small>
            まだアカウントを持ってないですか？ <a href="{{ url_for('users.createaccount') }}" class="need_account">アカウント作成へ</a>
        </small>
    </div>

{% endblock %}

classget/templates/users/mypage.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/mypage.css') }}" type="text/css">
{% endblock %}

{% block contents %}
    <div class="userinfo">
        <img class="userimg" src="{{ image_file }}">
        <span class="username">
            {{ current_user.username }}
        </span>
        <span class="type">
            {{ current_user.type }}タイプ大学生
        </span>
        <div class="faculty/year">
            <span class="faculty">
                {{ current_user.faculty }}
            </span>
            <span class="year">
                {{ current_user.year }}年生
            </span>
        </div>
    </div>
    <div class="update">
        <a href="{{ url_for('users.updateaccount') }}">アカウント情報修正</a>
    </div>

    <!-- ここに時間割作ってください -->
    <div class="select-season">
        {% for i in ['春', '夏', '秋', '冬'] %}
            {% if i == my_term %}
                <div class="{{ i }}", id="current_term">
                    <a href="{{ url_for('users.mypage', my_term=i) }}"><button>{{ i }}学期</button></a>
                </div>
            {% else %}
                <div class="{{ i }}">
                    <a href="{{ url_for('users.mypage', my_term=i) }}"><button>{{ i }}学期</button></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="timetable">
        <table class="timetable">
            <tr>
                <th class="space"></th>
                <th>月</th>
                <th>火</th>
                <th>水</th>
                <th>木</th>
                <th>金</th>
            </tr>

            <tr>
                <td class="jigen">1</td>
                <td class="mo1">
                    {% for i in timetable('月1') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu1">
                    {% for i in timetable('火1') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we1">
                    {% for i in timetable('水1') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th1">
                    {% for i in timetable('木1') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr1">
                    {% for i in timetable('金1') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>

            <tr>
                <td class="jigen">2</td>
                <td class="mo2">
                    {% for i in timetable('月2') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu2">
                    {% for i in timetable('火2') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we2">
                    {% for i in timetable('水2') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th2">
                    {% for i in timetable('木2') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr2">
                    {% for i in timetable('金2') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>

            <tr>
                <td class="jigen">3</td>
                <td class="mo3">
                    {% for i in timetable('月3') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu3">
                    {% for i in timetable('火3') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we3">
                    {% for i in timetable('水3') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th3">
                    {% for i in timetable('木3') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr3">
                    {% for i in timetable('金3') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>

            <tr>
                <td class="jigen">4</td>
                <td class="mo4">
                    {% for i in timetable('月4') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu4">
                    {% for i in timetable('火4') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we4">
                    {% for i in timetable('水4') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th4">
                    {% for i in timetable('木4') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr4">
                    {% for i in timetable('金4') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>

            <tr>
                <td class="jigen">5</td>
                <td class="mo5">
                    {% for i in timetable('月5') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu5">
                    {% for i in timetable('火5') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we5">
                    {% for i in timetable('水5') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th5">
                    {% for i in timetable('木5') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr5">
                    {% for i in timetable('金5') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>

            <tr>
                <td class="jigen">6</td>
                <td class="mo6">
                    {% for i in timetable('月6') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu6">
                    {% for i in timetable('火6') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we6">
                    {% for i in timetable('水6') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th6">
                    {% for i in timetable('木6') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr6">
                    {% for i in timetable('金6') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>
            
            <tr>
                <td class="jigen">7</td>
                <td class="mo7">
                    {% for i in timetable('月7') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="tu7">
                    {% for i in timetable('火7') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="we7">
                    {% for i in timetable('水7') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="th7">
                    {% for i in timetable('木7') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
                <td class="fr7">
                    {% for i in timetable('金7') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>
            
            <tr>
                <td class="jigen">他</td>
                <td class="etc" colspan="5">
                    {% for i in timetable('他') %}
                        <a href="{{ url_for('reviews.classinfo', subject_id=i[0]) }}"><p>{{ i[1] }}</p></a>
                    {% endfor %}
                </td>
            </tr>
        </table>
    </div>
    {% if current_user.is_authenticated and current_user.iduser == 'admin' %}
        <div>
	    ・ユーザー数：{{ get_count(User.query) }}
        </div>
	<div>
            ・レビュー数：{{ get_count(Review.query) }}
        </div>
    {% endif %}
{% endblock contents %}