classget/reviews/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectMultipleField, widgets, StringField, RadioField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class ReviewForm(FlaskForm):
    keyword_choices = [('期末試験', '期末試験'), ('期末レポート', '期末レポート'), ('中間試験', '中間試験'),
               ('中間レポート', '中間レポート'), ('出席', '出席'), ('課題(毎回)', '課題(毎回)'), ('課題(たまに)', '課題(たまに)'),
               ('ライブ', 'ライブ'), ('オンデマンド', 'オンデマンド'), ('ライブ・オンデマ併用', 'ライブ・オンデマ併用'), ('対面', '対面'),
               ('顔出しアリ', '顔出しアリ'), ('顔出しナシ', '顔出しナシ'),('今年度非開講','今年度非開講')]
    title = StringField('タイトル*', validators=[DataRequired(), Length(max=15)])
    rating = RadioField('評　価*', choices=[(0, 'good'), (1, 'soso'), (2, 'bad')])
    content = TextAreaField('本　文*', validators=[DataRequired()])
    keyword = MultiCheckboxField('キーワード', choices=keyword_choices)
    submit = SubmitField('投 稿')

    def validate_title(self, title):
        if len(title.data) > 15:
            raise ValidationError('タイトルは15字以内で書いてください')

classget/admin/routes.py
from flask import Blueprint, url_for, request, render_template
from flask_login import current_user
from werkzeug.utils import redirect

from classget import db
from classget.admin.forms import UpdateClassForm
from classget.models import Subject

admin = Blueprint('admin', __name__)


@admin.route("/updateclass/<int:subject_id>", methods=["GET", "POST"])
def updateclass(subject_id):
    # UserIDが「admin」の場合だけ
    if current_user.is_authenticated and current_user.iduser == 'admin':
        subject = Subject.query.get_or_404(subject_id)
        form = UpdateClassForm()
        # 修正フォームが提出されたら、DBに適用する
        if form.validate_on_submit():
            subject.sort = form.sort.data
            subject.term = form.term.data
            subject.time = form.time.data
            subject.name = form.name.data
            subject.teacher = form.teacher.data
            subject.language = form.language.data
            subject.draw = form.draw.data
            subject.keyword = form.keyword.data
            db.session.commit()
            return redirect(url_for('reviews.classinfo', subject_id=subject_id))
        # ページを開いたら既存の情報がすでに入っている
        elif request.method == 'GET':
            form.sort.data = subject.sort
            form.term.data = subject.term
            form.time.data = subject.time
            form.name.data = subject.name
            form.teacher.data = subject.teacher
            form.language.data = subject.language
            form.draw.data = subject.draw
            form.keyword.data = subject.keyword
            return render_template('admin/update_class.html', subject=subject, form=form)
    else:
        return 'access denied'


@admin.route("/createclass", methods=["GET", "POST"])
def createclass():
    form = UpdateClassForm()
    if current_user.is_authenticated and current_user.iduser == 'admin':
        if form.validate_on_submit():
            new_subject = Subject(sort=form.sort.data, term=form.term.data, time=form.time.data, name=form.name.data,
                                  teacher=form.teacher.data, language=form.language.data, draw=form.draw.data,
                                  keyword=form.keyword.data)
            db.session.add(new_subject)
            db.session.commit()
            return redirect(url_for('reviews.classinfo', subject_id=new_subject.id))
    else:
        return 'access denied'

    return render_template('admin/createclass.html', form=form)

@admin.route("/report.html")
def report_html():
    return render_template('report.html')

classget/main/routes.py
import os

from flask import Blueprint, render_template, session, request, send_from_directory, current_app
from flask_login import current_user
from sqlalchemy import or_

from classget.main.forms import SearchClassForm
from classget.models import Subject, get_count, Review

main = Blueprint('main', __name__)


@main.route("/", methods=["GET", "POST"])
def mainpage():
    form = SearchClassForm()
    return render_template('main/mainpage.html', form=form)


@main.route("/searchresult", methods=['GET', 'POST'])
def searchresult():
    form = SearchClassForm()
    result = Subject.query
    if form.validate_on_submit():
        session['form.sort.data'] = form.sort.data
        session['form.term.data'] = form.term.data
        session['form.day.data'] = form.day.data
        session['form.time.data'] = form.time.data
        session['form.draw.data'] = form.draw.data
        session['form.title.data'] = form.title.data
        session['form.teacher.data'] = form.teacher.data
        session['form.keyword.data'] = form.keyword.data
    # 所属
    if session['form.sort.data']:
        result = result.filter(Subject.sort.in_(session['form.sort.data']))
    # 開講区分
    if session['form.term.data']:
        result = result.filter(Subject.term.in_(session['form.term.data']))
    # 曜日
    if session['form.day.data']:
        day = [0, 0, 0, 0, 0, 0]
        for i in range(len(session['form.day.data'])):
            day[i] = session['form.day.data'][i]
        result = result.filter(or_(Subject.time.like(f'%{day[0]}%'), Subject.time.like(f'%{day[1]}%'),
                                   Subject.time.like(f'%{day[2]}%'), Subject.time.like(f'%{day[3]}%'),
                                   Subject.time.like(f'%{day[4]}%'), Subject.time.like(f'%{day[5]}%')))
    # 時限
    if session['form.time.data']:
        time = [0, 0, 0, 0, 0, 0]
        for i in range(len(session['form.time.data'])):
            time[i] = session['form.time.data'][i]
        result = result.filter(or_(Subject.time.like(f'%{time[0]}%'), Subject.time.like(f'%{time[1]}%'),
                                   Subject.time.like(f'%{time[2]}%'), Subject.time.like(f'%{time[3]}%'),
                                   Subject.time.like(f'%{time[4]}%'), Subject.time.like(f'%{time[5]}%')))
    # 抽選
    if session['form.draw.data']:
        result = result.filter(Subject.draw.in_(session['form.draw.data']))
    # 授業名
    if session['form.title.data']:
        result = result.filter(Subject.name.like(f"%{session['form.title.data']}%"))
    # 教授名
    if session['form.teacher.data']:
        result = result.filter(Subject.teacher.like(f"%{session['form.teacher.data']}%"))
    # キーワード
    if session['form.keyword.data']:
        for keyword in session['form.keyword.data']:
            result = result.filter(Subject.keyword.notlike(f'%{keyword}%'))
    # 検索結果を１０個ずつ分けてページを作る
    page = request.args.get('page', 1, type=int)
    result_num = get_count(result)
    result = result.paginate(page=page, per_page=10)
    if not result:
        result = "検索結果がありません。"
    return render_template('main/searchresult.html', title='検索結果', result=result, get_count=get_count, form=form,
                           Review=Review, result_num=result_num)


@main.route('/about_us')
def aboutus():
    return render_template('main/aboutus.html', title='About Us')


@main.route('/ham_menu', methods=['POST'])
def ham_menu():
    action = request.form['action']
    if action == 'show_menu':
        if current_user.is_authenticated:
            return render_template('main/show_ham_menu.html')
        else:
            return render_template('main/nouser_show_ham_menu.html')
    elif action == 'close_menu':
        return render_template('main/close_ham_menu.html')
    else:
        pass


@main.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static/img/icon'), 'favicon.ico',
                               mimetype='image/vnd.microsoft.icon')


@main.route('/sw.js')
def sw_js():
    return send_from_directory(os.path.join(current_app.root_path, 'static/js'), 'sw.js')


@main.route('/mobile_install')
def mobile_install():
    return render_template('main/mobile_install.html')

classget/reviews/routes.py
import smtplib
import yaml
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from flask import Blueprint, request, url_for, render_template
from flask_login import current_user
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from classget import db
from classget.admin.forms import UpdateClassForm
from classget.models import Subject, Review, get_count
from classget.reviews.forms import ReviewForm

reviews = Blueprint('reviews', __name__)
yml = yaml.load(open('classget/configure.yaml'), Loader=yaml.BaseLoader)


@reviews.route("/classinfo/<int:subject_id>", methods=["GET", "POST"])
def classinfo(subject_id):
    # PKのIDでその授業の情報を持ってくる
    subject = Subject.query.get_or_404(subject_id)
    page = request.args.get('page', 1, type=int)
    form = ReviewForm()
    subject_keyword = subject.keyword.split('　')
    # 授業IDでその授業のレビューを全部持ってくる
    reviews = Review.query.filter_by(subject_id=subject_id).order_by(Review.date_posted.desc())
    reviews_num = get_count(reviews)
    reviews = reviews.paginate(page=page, per_page=5)
    # レビューに基づいたおすすめ授業（３つ）
    recommended = subject.recommended_by_review()
    # レビューフォームを提出したら
    if form.validate_on_submit():
        # ログインしている場合
        if current_user.is_authenticated:
            # キーワードをListから一つのStringにする
            keywords = ' '.join([str(i) for i in form.keyword.data])
            # レビューをデータベースに入れる
            review = Review(title=form.title.data, rating=form.rating.data, content=form.content.data,
                            keyword=keywords, author=current_user, subject_id=subject_id)
            db.session.add(review)
            db.session.commit()
            return redirect(request.referrer)
        # ログインしていない場合→ログイン画面へ
        else:
            return redirect(url_for('users.login'))
    return render_template('reviews/classinfo.html', title=subject.name, subject=subject, form=form, reviews=reviews,
                           enumerate=enumerate, subject_keyword=subject_keyword, get_count=get_count, Review=Review,
                           recommended=recommended, reviews_num=reviews_num)


@reviews.route("/delete_review/<int:review_id>_<int:subject_id>", methods=["GET"])
def delete_review(review_id, subject_id):
    review = Review.query.get_or_404(review_id)
    if review.author != current_user:
        abort(403)
    db.session.delete(review)
    db.session.commit()
    return redirect(url_for('reviews.classinfo', subject_id=subject_id))


@reviews.route("/report/<int:subject_id>", methods=["GET", "POST"])
def report(subject_id):
    subject = Subject.query.get_or_404(subject_id)
    form = UpdateClassForm()
    if form.validate_on_submit():
        # 送信者情報
        sender = "machikado.cookingclass@gmail.com"
        sender_password = yml['email_pw']
        # メールサーバーにログイン
        s = smtplib.SMTP_SSL('smtp.gmail.com')
        s.login(sender, sender_password)
        # 宛名
        receiver = "hit.classget@gmail.com"
        # メール送信情報
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "ユーザーからの授業情報修正の報告"
        msg['From'] = sender
        msg['To'] = receiver
        # メール本文
        content = f'''
        ・開講区分：{form.sort.data}
        ・学期：{form.term.data}
        ・曜日時限：{form.time.data}
        ・授業名：{form.name.data}
        ・教授名：{form.teacher.data}
        ・言語：{form.language.data}
        ・抽選：{form.draw.data}
        ・キーワード：{form.keyword.data}
        '''
        part2 = MIMEText(content, 'plain')
        msg.attach(part2)
        # メール送信、サーバーを閉じる
        s.sendmail(sender, receiver, msg.as_string())
        s.quit()
        return render_template('reviews/report_complete.html')
    # ページを開いたら既存の情報がすでに入っている
    elif request.method == 'GET':
        form.sort.data = subject.sort
        form.term.data = subject.term
        form.time.data = subject.time
        form.name.data = subject.name
        form.teacher.data = subject.teacher
        form.language.data = subject.language
        form.draw.data = subject.draw
        form.keyword.data = subject.keyword
    return render_template('reviews/report.html', subject=subject, form=form, title='授業情報報告')

classget/templates/reviews/classinfo.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/classinfo.css') }}" type="text/css">
{% endblock %}


{% block contents %}
<!-- ここから授業詳細 -->
    <div class="warning">*一部の授業は取れる学年に制限があったり、年によって未開講だったりすることがあります。詳細はCELSの公式シラバスを確認してください。</div>
    <fieldset class="outer" id="top">
        <div class="classinfo">
            <div class="box">
<!--      授業名      -->
                <div class="main-info">
                    <h1 class="name">{{ subject.name }}</h1>
                    <!--   学期と曜日・時限   -->
                    <div class="term-and-time"><h3>{{ subject.term}} {{ subject.time }}</h3></div>
                </div>
                <!--  お気に入りボタン    -->
                <div class="like_buttons{{ subject.id }}">
<!--       お気に入り済みの状態         -->
                    {% if current_user.is_authenticated and current_user.has_liked_subject(subject) %}
                        <a href="" class="user_like_button" id="unlike_{{ subject.id }}">
                            <img class="like-button-img" src="{{ url_for('static', filename='img/system/liked.png') }}" width="35px">
                        </a>
<!--       お気に入りしてない状態        -->
                    {% elif current_user.is_authenticated %}
                        <a href="" class="user_like_button" id="like_{{ subject.id }}">
                            <img class="like-button-img" src="{{ url_for('static', filename='img/system/unliked.png') }}" width="35px">
                        </a>
<!--       ログインしてない状態（押したらログインページに送る）      -->
                    {% else %}
                        <a href="{{ url_for('users.login') }}" class="like_button">
                            <img class="like-button-img" src="{{ url_for('static', filename='img/system/unliked.png') }}" width="35px">
                        </a>
                    {% endif %}
                </div>
            </div>
    <!--　　授業情報　　-->
            <p class="sort">•{{ subject.sort }} <span class="draw">•{{ subject.draw }}</span></p>
            <p class="professor-and-language">•教員名：{{ subject.teacher }} 教授  <span class="draw">•言語：{{ subject.language }}</span></p>
    <!--   ３段階の顔文字評価の集計   -->
            <div class="class-rating">
            <img class="face-top" src="{{ url_for('static', filename='img/system/rating_0.png') }}"> {{ subject.rating_count(0) }}
            <img class="face-top" src="{{ url_for('static', filename='img/system/rating_1.png') }}"> {{ subject.rating_count(1) }}
            <img class="face-top" src="{{ url_for('static', filename='img/system/rating_2.png') }}"> {{ subject.rating_count(2) }}
                <span class="liked_number">(お気に入り {{ get_count(subject.likes) }}件)</span>
            </div>
<!--    キーワード      -->
            <div class="keywords">
                {% for keyword in subject_keyword %}
                    <span class="keyword">{{ keyword }}</span>
                {% endfor %}
            </div>
<!--    授業情報修正申請ボタン    -->
	    <div class="report">
                <a href="{{ url_for('reviews.report', subject_id=subject.id) }}"><button class="report_button">この授業の最新情報報告</button></a>
            </div>    
	    <div class="report">
                <a href="{{ url_for('main.searchresult') }}"><button class="go_back_button">検索結果に戻る</button></a>
            </div>
        </div>
<!--  授業情報修正ボタン（adminアカウントにだけ見える）  -->
        {% if current_user.is_authenticated and current_user.iduser == 'admin' %}
            <a href="{{ url_for('admin.updateclass', subject_id=subject.id) }}"><button class="update_class_button">授業情報修正</button></a>
        {% endif %}
    </fieldset>

<!-- ここからレビュー一覧 -->
    <fieldset class="outer">
        <div class="reviews">過去のレビュー<span class="review-num">：{{ reviews_num }}件</span></div>
        {% if reviews.items %}
            {% for review in reviews.items %}
                <fieldset class="inner">
<!--　　　　レビュー作成者　　　　　-->
                    <div class="author">
<!--      作成者アイコン       -->
                        <img class="user-icon" src="{{ url_for('static', filename='img/profile_pics/{}.png'.format(review.author.type)) }}">
<!--      作成者のユーザー名       -->
                        <div class="user-username">{{ review.author.username }}</div>
<!--      作成者の学部       -->
                        <div class="user-faculty">{{ review.author.faculty }}</div>
                    </div>
<!--　　　　レビュー内容　　　　　　-->
                    <div class="review-body">
<!--      タイトル         -->
                        <span class="review-title">{{ review.title }}</span>
<!--       評価     -->
                        <img class="review_face" src="{{ url_for('static', filename='img/system/rating_{}.png'.format(review.rating)) }}">
<!--       投稿日付         -->
                        <div class="uploaded_date">
                            {{ review.date_posted.strftime('%Y-%m-%d') }}
                        </div>
                        <hr>
<!--       本文       -->
                        <div class="review-content">{{ review.content }}</div>
<!--       キーワード         -->
                        <div class="review-keywords">
                        {% if review.keyword %}
                            {% for keyword in review.keyword.split(" ") %}
                                <span class="keyword">{{ keyword }}</span>
                            {% endfor %}
                        {% endif %}
                        </div>
<!--       レビュー削除ボタン（ログインしてるユーザー　＝＝　投稿者の場合）         -->
                        {% if review.author == current_user %}
                            <form class="delete-button" action="{{ url_for('reviews.delete_review', review_id=review.id, subject_id=subject.id) }}">
                                <button class="review-delete" type="submit">このレビューを削除</button>
                            </form>
                        {% endif %}
                    </div>
                </fieldset>
            {% endfor %}
<!--   レビューがないとき   -->
        {% else %}
            <div>作成されたレビューがありません。</div>
        {% endif %}
<!--   ページの表示   -->
        <div class="page_nums">
            {% for page_num in reviews.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if reviews.page == page_num %}
                        <a class="current_page_num" href="{{ url_for('reviews.classinfo', subject_id=subject.id, page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="page_num" href="{{ url_for('reviews.classinfo', subject_id=subject.id, page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </fieldset>

  <!-- ここからレビュー作成 -->
    <fieldset class="outer">
      <div class="newreview">
        <div class="create-review"><h2>レビュー作成</h2></div><hr>
          <form method="POST" action="" class="newreview">
            {{ form.hidden_tag() }}
              <div class="title-review">
		{% if form.title.errors %}
                	{{ form.title.label(class="label-title") }}
                	{{ form.title(class="blank-title", placeholder="15字以内") }}
			<span class="error_message">タイトルは15字以内で書いてください</span>
		{% else %}
			{{ form.title.label(class="label-title") }}
                        {{ form.title(class="blank-title", placeholder="15字以内") }}
		{% endif %}
              </div>

              <div class="rating-review">
                {{ form.rating.label(class="label-rating") }}
                {% for l, i in enumerate(form.rating) %}
                  <img class="face-top" src="{{ url_for('static', filename='img/system/rating_{}.png'.format(l)) }}"> {{ i(class="button") }}
                {% endfor %}
              </div>

              <div class="content-review">
                {{ form.content.label(class="label-content") }}
                {{ form.content(class="blank-content") }}
              </div>

              <div class="keyword-review">
                {{ form.keyword.label(class="label-keyword") }}
                <div class="select-keyword">
                    {{ form.keyword(class="blank-keyword") }}
                </div>
              </div>

              <div class="submit-review">
                {{ form.submit }}
              </div>
          </form>
      </div>
    </fieldset>

    <div class="suggestion">
        <p class="suggestion">この授業に<img class="face_heading" src="{{ url_for('static', filename='/img/system/rating_0.png') }}">レビューを書いた人は、
            <br>こちらの授業にも<img class="face_heading" src="{{ url_for('static', filename='/img/system/rating_0.png') }}">レビューを書きました<hr class="sug-hr"></p>

        <div class="cream-box">
            {% for subject in recommended %}
                {% if subject %}
                    <div class="class-sug">
                        <p class="class_name">{{ subject.name }}</p>
                        <p class="term_day">
                            {{ subject.term }}　{{ subject.time }}
                            {% if current_user.is_authenticated and current_user.has_liked_subject(subject) %}
                                <img class="like_button" src="{{ url_for('static', filename='/img/system/liked.png') }}">
                            {% else %}
                                <img class="like_button" src="{{ url_for('static', filename='/img/system/unliked.png') }}">
                            {% endif %}
                        </p>
                        <hr class="sug-line">
                        <div class="flex-box">
                            <img class="face" src="{{ url_for('static', filename='/img/system/rating_0.png') }}">
                            <p class="rating-number">{{ subject.rating_count(0) }}</p>
                            <img class="face" src="{{ url_for('static', filename='/img/system/rating_1.png') }}">
                            <p class="rating-number">{{ subject.rating_count(1) }}</p>
                            <img class="face" src="{{ url_for('static', filename='/img/system/rating_2.png') }}">
                            <p class="rating-number">{{ subject.rating_count(2) }}</p>
                        </div>
                        <p class="favorite">お気に入り{{ get_count(subject.likes) }}件</p>
                        <a class="link-classinfo" href="{{ url_for('reviews.classinfo', subject_id=subject.id) }}"><p class="link-classinfo">授業詳細へ</p></a>
                    </div>
                {% else %}
                    <div class="class-sug">
                        <div class="no-data">まだデータがありません</div>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/like_button.js') }}"></script>
{% endblock %}

classget/templates/reviews/report.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/updateclass.css') }}" type="text/css">
{% endblock %}

{% block contents %}

    <form method="POST" action="">
            {{ form.hidden_tag() }}
            <h2>授業の最新情報を報告</h2>
            <fieldset>
                <!--       sort         -->
                <div class="sort">
                    {{ form.sort.label }}
                    {{ form.sort }}
                </div>

                <!--       term         -->
                <div class="term">
                    {{ form.term.label }}
                    {{ form.term }}
                </div>

                <!--       time         -->
                <div class="time">
                    {{ form.time.label }}
                    {{ form.time }}
                    <span class="warning">*曜日は漢字、時限は数字</span>
                </div>

                <!--       name         -->
                <div class="name">
                    {{ form.name.label }}
                    {{ form.name }}
                    <span class="warning">*略称不可</span>
                </div>

                <!--       teacher         -->
                <div class="teacher">
                    {{ form.teacher.label }}
                    {{ form.teacher }}
                </div>

                <!--       language         -->
                <div class="language">
                    {{ form.language.label }}
                    {{ form.language }}
                </div>

                <!--       draw         -->
                <div class="draw">
                    {{ form.draw.label }}
                    {{ form.draw }}
                    <span class="warning">*抽選科目または抽選なし</span>
                </div>

                <!--       keyword         -->
                <div class="keyword">
                    {{ form.keyword.label }}
                    {{ form.keyword }}
                    <span class="warning">*該当するキーワードを全て書いてください</span>
                    <div class="keywords">*キーワード：期末試験　期末レポート　中間試験　中間レポート　出席　課題(毎回)　課題(たまに)　ライブ　オンデマンド　ライブ・オンデマ併用　対面　顔出しアリ　顔出しナシ</div>
                </div>

            </fieldset>

            <!--     submit       -->
            <div class="submit_button">
                {{ form.submit(class="submit_button", value="この情報で報告!") }}
            </div>
        </form>

{% endblock %}

classget/templates/reviews/report_complete.html
{% extends 'main/layout.html' %}

{% block stylesheet %}
<!-- ここにCSSファイルをリンクする -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/updateclass.css') }}" type="text/css">
{% endblock %}

{% block contents %}

    <h1>報告が送信されました。ありがとうございます。</h1>

{% endblock %}